import AppKit
import Observation
import os

private let logger = Logger(subsystem: "io.github.satis-ku.eyelid", category: "Clipboard")

/// The last things copied, newest first, after the pinned ones. Kept in memory only, so the history is gone when
/// Eyelid quits, except for pinned copies, which are saved.
@MainActor
@Observable
final class ClipboardHistory {
    /// How many copies the history keeps, not counting pinned ones.
    static let maxEntries = 50
    /// Copies larger than this are left out rather than kept in memory.
    static let maxEntrySize = 20 * 1024 * 1024

    /// The types kept from each pasteboard item: enough to put back text with its formatting, links, files and images.
    static let keptTypes: [NSPasteboard.PasteboardType] = [.fileURL, .URL, .string, .rtf, .html, .png, .tiff]

    /// Markers that apps put on copies not meant to be kept, from nspasteboard.org: passwords from password
    /// managers, and data that's only on the pasteboard for a moment or that an app made up on its own.
    static let skippedMarkers: Set<NSPasteboard.PasteboardType> = Set([
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ].map { NSPasteboard.PasteboardType(rawValue: $0) })

    /// Whether macOS lets Eyelid read what other apps copy.
    enum Access {
        case allowed
        /// macOS asks every time, which a history can't work with.
        case ask
        case denied
        /// Eyelid has never read the pasteboard, so it isn't in System Settings yet.
        case notAskedYet
    }

    private(set) var entries: [ClipboardEntry] = []

    @ObservationIgnored private let pasteboard: NSPasteboard
    @ObservationIgnored private var lastChangeCount: Int
    @ObservationIgnored private var monitorTask: Task<Void, Never>?
    /// Where pinned copies are saved, or nil to keep them in memory too.
    @ObservationIgnored private let pinnedFile: URL?

    init(pasteboard: NSPasteboard = .general, pinnedFile: URL?) {
        self.pasteboard = pasteboard
        self.pinnedFile = pinnedFile
        lastChangeCount = pasteboard.changeCount
        entries = loadPinned()
    }

    static var defaultPinnedFile: URL {
        URL.applicationSupportDirectory.appending(path: "io.github.satis-ku.eyelid/Clipboard/Pinned.plist")
    }

    var pinnedCount: Int {
        entries.count { $0.isPinned }
    }

    /// Since macOS 15.4 the user decides in Privacy & Security → Paste from Other Apps.
    var access: Access {
        guard #available(macOS 15.4, *) else { return .allowed }
        switch pasteboard.accessBehavior {
        case .alwaysAllow: return .allowed
        case .alwaysDeny: return .denied
        case .default: return .notAskedYet
        case .ask: return .ask
        @unknown default: return .ask
        }
    }

    // MARK: - Watching the pasteboard

    /// macOS has no notification for copies, so the change count is checked twice a second. That alone needs
    /// no permission, and the contents are only read after a change.
    func setMonitoring(_ isOn: Bool) {
        monitorTask?.cancel()
        monitorTask = nil
        guard isOn else { return }

        lastChangeCount = pasteboard.changeCount
        monitorTask = Task { [weak self] in
            while !Task.isCancelled {
                try? await Task.sleep(for: .milliseconds(500))
                self?.checkForChanges()
            }
        }
    }

    /// Adds the pasteboard's contents if they changed since the last look, and if macOS allows reading them
    /// without asking: asking on every copy would make the history unusable.
    func checkForChanges() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        guard access == .allowed else { return }
        captureCurrentContents()
    }

    /// Reads what's on the pasteboard now. Unless Eyelid is allowed to, macOS asks the user first, which also
    /// lists Eyelid under Paste from Other Apps.
    func captureCurrentContents() {
        lastChangeCount = pasteboard.changeCount
        if let entry = readEntry() {
            add(entry)
        }
    }

    private func readEntry() -> ClipboardEntry? {
        guard let types = pasteboard.types, Self.skippedMarkers.isDisjoint(with: types) else { return nil }

        var size = 0
        var items: [[NSPasteboard.PasteboardType: Data]] = []
        for item in pasteboard.pasteboardItems ?? [] {
            var kept: [NSPasteboard.PasteboardType: Data] = [:]
            for type in Self.keptTypes where item.types.contains(type) {
                guard let data = item.data(forType: type) else { continue }
                kept[type] = data
                size += data.count
            }
            if !kept.isEmpty {
                items.append(kept)
            }
        }

        guard size <= Self.maxEntrySize else {
            logger.info("Left out a copy of \(size, privacy: .public) bytes")
            return nil
        }
        return ClipboardEntry(items: items, sourceAppURL: NSWorkspace.shared.frontmostApplication?.bundleURL)
    }

    // MARK: - Changes

    /// Puts an entry first, after the pinned ones. Copying the same thing again moves its entry up rather than
    /// adding another, and a pinned copy stays where it is.
    func add(_ entry: ClipboardEntry) {
        if let index = entries.firstIndex(where: { $0.isPinned && $0.hasSameContent(as: entry) }) {
            entries[index].date = entry.date
            return
        }
        entries.removeAll { $0.hasSameContent(as: entry) }
        var entry = entry
        entry.isPinned = false
        entries.insert(entry, at: pinnedCount)

        let unpinned = entries.count - pinnedCount
        if unpinned > Self.maxEntries {
            entries.removeLast(unpinned - Self.maxEntries)
        }
    }

    /// Pinning moves a copy to the top, unpinning to the top of the others.
    func setPinned(_ id: ClipboardEntry.ID, _ isPinned: Bool) {
        guard let index = entries.firstIndex(where: { $0.id == id }), entries[index].isPinned != isPinned else { return }
        var entry = entries.remove(at: index)
        entry.isPinned = isPinned
        entries.insert(entry, at: isPinned ? 0 : pinnedCount)
        savePinned()
    }

    /// Puts an entry back on the pasteboard and moves it to the top.
    func copy(_ entry: ClipboardEntry) {
        let items = entry.items.map { representations in
            let item = NSPasteboardItem()
            for (type, data) in representations {
                item.setData(data, forType: type)
            }
            return item
        }
        pasteboard.clearContents()
        pasteboard.writeObjects(items)
        // Eyelid's own copy isn't a new entry.
        lastChangeCount = pasteboard.changeCount

        var moved = entry
        moved.date = .now
        add(moved)
    }

    func remove(_ id: ClipboardEntry.ID) {
        let wasPinned = entries.contains { $0.id == id && $0.isPinned }
        entries.removeAll { $0.id == id }
        if wasPinned {
            savePinned()
        }
    }

    /// Clears the history. Pinned copies stay until they're unpinned or removed one by one.
    func removeAll() {
        entries.removeAll { !$0.isPinned }
    }

    // MARK: - Pinned copies

    private func loadPinned() -> [ClipboardEntry] {
        guard let pinnedFile, let data = try? Data(contentsOf: pinnedFile) else { return [] }
        do {
            return try PropertyListDecoder().decode([ClipboardEntry.Stored].self, from: data)
                .compactMap(ClipboardEntry.init(stored:))
        } catch {
            logger.error("Could not read pinned copies: \(error.localizedDescription, privacy: .public)")
            return []
        }
    }

    private func savePinned() {
        guard let pinnedFile else { return }
        let pinned = entries.filter(\.isPinned).map(\.stored)
        do {
            if pinned.isEmpty {
                try? FileManager.default.removeItem(at: pinnedFile)
                return
            }
            try FileManager.default.createDirectory(
                at: pinnedFile.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
            let encoder = PropertyListEncoder()
            encoder.outputFormat = .binary
            try encoder.encode(pinned).write(to: pinnedFile, options: .atomic)
        } catch {
            logger.error("Could not save pinned copies: \(error.localizedDescription, privacy: .public)")
        }
    }
}
