import AppKit
import Observation
import os

private let logger = Logger(subsystem: "io.github.nikita19329.eyelid", category: "Clipboard")

/// The last things copied, newest first. Kept in memory only, so the history is gone when Eyelid quits.
@MainActor
@Observable
final class ClipboardHistory {
    static let maxEntries = 50
    /// Copies larger than this are left out rather than kept in memory.
    static let maxEntrySize = 20 * 1024 * 1024

    /// The types kept from each pasteboard item: enough to put back text with its formatting, links, files and images.
    static let keptTypes: [NSPasteboard.PasteboardType] = [.fileURL, .URL, .string, .rtf, .html, .png, .tiff]

    /// Markers that apps put on copies not meant to be kept, from nspasteboard.org: passwords from password
    /// managers, and data that's only on the pasteboard for a moment or that an app made up on its own.
    static let skippedMarkers: Set<NSPasteboard.PasteboardType> = Set([
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ].map { NSPasteboard.PasteboardType(rawValue: $0) })

    /// Whether macOS lets Eyelid read what other apps copy.
    enum Access {
        case allowed
        /// macOS asks every time, which a history can't work with.
        case ask
        case denied
        /// Eyelid has never read the pasteboard, so it isn't in System Settings yet.
        case notAskedYet
    }

    private(set) var entries: [ClipboardEntry] = []

    @ObservationIgnored private let pasteboard: NSPasteboard
    @ObservationIgnored private var lastChangeCount: Int
    @ObservationIgnored private var monitorTask: Task<Void, Never>?

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
    }

    /// Since macOS 15.4 the user decides in Privacy & Security → Paste from Other Apps.
    var access: Access {
        guard #available(macOS 15.4, *) else { return .allowed }
        switch pasteboard.accessBehavior {
        case .alwaysAllow: return .allowed
        case .alwaysDeny: return .denied
        case .default: return .notAskedYet
        case .ask: return .ask
        @unknown default: return .ask
        }
    }

    // MARK: - Watching the pasteboard

    /// macOS has no notification for copies, so the change count is checked twice a second. That alone needs
    /// no permission, and the contents are only read after a change.
    func setMonitoring(_ isOn: Bool) {
        monitorTask?.cancel()
        monitorTask = nil
        guard isOn else { return }

        lastChangeCount = pasteboard.changeCount
        monitorTask = Task { [weak self] in
            while !Task.isCancelled {
                try? await Task.sleep(for: .milliseconds(500))
                self?.checkForChanges()
            }
        }
    }

    /// Adds the pasteboard's contents if they changed since the last look, and if macOS allows reading them
    /// without asking: asking on every copy would make the history unusable.
    func checkForChanges() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        guard access == .allowed else { return }
        captureCurrentContents()
    }

    /// Reads what's on the pasteboard now. Unless Eyelid is allowed to, macOS asks the user first, which also
    /// lists Eyelid under Paste from Other Apps.
    func captureCurrentContents() {
        lastChangeCount = pasteboard.changeCount
        if let entry = readEntry() {
            add(entry)
        }
    }

    private func readEntry() -> ClipboardEntry? {
        guard let types = pasteboard.types, Self.skippedMarkers.isDisjoint(with: types) else { return nil }

        var size = 0
        var items: [[NSPasteboard.PasteboardType: Data]] = []
        for item in pasteboard.pasteboardItems ?? [] {
            var kept: [NSPasteboard.PasteboardType: Data] = [:]
            for type in Self.keptTypes where item.types.contains(type) {
                guard let data = item.data(forType: type) else { continue }
                kept[type] = data
                size += data.count
            }
            if !kept.isEmpty {
                items.append(kept)
            }
        }

        guard size <= Self.maxEntrySize else {
            logger.info("Left out a copy of \(size, privacy: .public) bytes")
            return nil
        }
        return ClipboardEntry(items: items, sourceAppURL: NSWorkspace.shared.frontmostApplication?.bundleURL)
    }

    // MARK: - Changes

    /// Puts an entry first. Copying the same thing again moves its entry up rather than adding another.
    func add(_ entry: ClipboardEntry) {
        entries.removeAll { $0.hasSameContent(as: entry) }
        entries.insert(entry, at: 0)
        if entries.count > Self.maxEntries {
            entries.removeLast(entries.count - Self.maxEntries)
        }
    }

    /// Puts an entry back on the pasteboard and moves it to the top.
    func copy(_ entry: ClipboardEntry) {
        let items = entry.items.map { representations in
            let item = NSPasteboardItem()
            for (type, data) in representations {
                item.setData(data, forType: type)
            }
            return item
        }
        pasteboard.clearContents()
        pasteboard.writeObjects(items)
        // Eyelid's own copy isn't a new entry.
        lastChangeCount = pasteboard.changeCount

        var moved = entry
        moved.date = .now
        add(moved)
    }

    func remove(_ id: ClipboardEntry.ID) {
        entries.removeAll { $0.id == id }
    }

    func removeAll() {
        entries.removeAll()
    }
}
